/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveysIndexRouteImport } from './routes/surveys/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminResponsesRouteImport } from './routes/admin/responses'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCreateRouteImport } from './routes/admin/create'
import { Route as SurveysSurveyIdIndexRouteImport } from './routes/surveys/$surveyId.index'
import { Route as AdminSurveysIndexRouteImport } from './routes/admin/surveys/index'
import { Route as SurveysSurveyIdPrintRouteImport } from './routes/surveys/$surveyId.print'
import { Route as SurveysSurveyIdFillRouteImport } from './routes/surveys/$surveyId.fill'
import { Route as SurveysSurveyIdChatRouteImport } from './routes/surveys/$surveyId.chat'
import { Route as AdminSurveysSurveyIdIndexRouteImport } from './routes/admin/surveys/$surveyId.index'
import { Route as AdminSurveysSurveyIdPrintRouteImport } from './routes/admin/surveys/$surveyId.print'
import { Route as AdminSurveysSurveyIdFillRouteImport } from './routes/admin/surveys/$surveyId.fill'
import { Route as AdminSurveysSurveyIdChatRouteImport } from './routes/admin/surveys/$surveyId.chat'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIndexRoute = SurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResponsesRoute = AdminResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRoute,
} as any)
const SurveysSurveyIdIndexRoute = SurveysSurveyIdIndexRouteImport.update({
  id: '/surveys/$surveyId/',
  path: '/surveys/$surveyId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSurveysIndexRoute = AdminSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => AdminRoute,
} as any)
const SurveysSurveyIdPrintRoute = SurveysSurveyIdPrintRouteImport.update({
  id: '/surveys/$surveyId/print',
  path: '/surveys/$surveyId/print',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysSurveyIdFillRoute = SurveysSurveyIdFillRouteImport.update({
  id: '/surveys/$surveyId/fill',
  path: '/surveys/$surveyId/fill',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysSurveyIdChatRoute = SurveysSurveyIdChatRouteImport.update({
  id: '/surveys/$surveyId/chat',
  path: '/surveys/$surveyId/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSurveysSurveyIdIndexRoute =
  AdminSurveysSurveyIdIndexRouteImport.update({
    id: '/surveys/$surveyId/',
    path: '/surveys/$surveyId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSurveysSurveyIdPrintRoute =
  AdminSurveysSurveyIdPrintRouteImport.update({
    id: '/surveys/$surveyId/print',
    path: '/surveys/$surveyId/print',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSurveysSurveyIdFillRoute =
  AdminSurveysSurveyIdFillRouteImport.update({
    id: '/surveys/$surveyId/fill',
    path: '/surveys/$surveyId/fill',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSurveysSurveyIdChatRoute =
  AdminSurveysSurveyIdChatRouteImport.update({
    id: '/surveys/$surveyId/chat',
    path: '/surveys/$surveyId/chat',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/surveys/$surveyId/chat': typeof SurveysSurveyIdChatRoute
  '/surveys/$surveyId/fill': typeof SurveysSurveyIdFillRoute
  '/surveys/$surveyId/print': typeof SurveysSurveyIdPrintRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/surveys/$surveyId/': typeof SurveysSurveyIdIndexRoute
  '/admin/surveys/$surveyId/chat': typeof AdminSurveysSurveyIdChatRoute
  '/admin/surveys/$surveyId/fill': typeof AdminSurveysSurveyIdFillRoute
  '/admin/surveys/$surveyId/print': typeof AdminSurveysSurveyIdPrintRoute
  '/admin/surveys/$surveyId/': typeof AdminSurveysSurveyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin': typeof AdminIndexRoute
  '/surveys': typeof SurveysIndexRoute
  '/surveys/$surveyId/chat': typeof SurveysSurveyIdChatRoute
  '/surveys/$surveyId/fill': typeof SurveysSurveyIdFillRoute
  '/surveys/$surveyId/print': typeof SurveysSurveyIdPrintRoute
  '/admin/surveys': typeof AdminSurveysIndexRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdIndexRoute
  '/admin/surveys/$surveyId/chat': typeof AdminSurveysSurveyIdChatRoute
  '/admin/surveys/$surveyId/fill': typeof AdminSurveysSurveyIdFillRoute
  '/admin/surveys/$surveyId/print': typeof AdminSurveysSurveyIdPrintRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/surveys/': typeof SurveysIndexRoute
  '/surveys/$surveyId/chat': typeof SurveysSurveyIdChatRoute
  '/surveys/$surveyId/fill': typeof SurveysSurveyIdFillRoute
  '/surveys/$surveyId/print': typeof SurveysSurveyIdPrintRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/surveys/$surveyId/': typeof SurveysSurveyIdIndexRoute
  '/admin/surveys/$surveyId/chat': typeof AdminSurveysSurveyIdChatRoute
  '/admin/surveys/$surveyId/fill': typeof AdminSurveysSurveyIdFillRoute
  '/admin/surveys/$surveyId/print': typeof AdminSurveysSurveyIdPrintRoute
  '/admin/surveys/$surveyId/': typeof AdminSurveysSurveyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/responses'
    | '/admin/signup'
    | '/admin/'
    | '/surveys/'
    | '/surveys/$surveyId/chat'
    | '/surveys/$surveyId/fill'
    | '/surveys/$surveyId/print'
    | '/admin/surveys/'
    | '/surveys/$surveyId/'
    | '/admin/surveys/$surveyId/chat'
    | '/admin/surveys/$surveyId/fill'
    | '/admin/surveys/$surveyId/print'
    | '/admin/surveys/$surveyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/responses'
    | '/admin/signup'
    | '/admin'
    | '/surveys'
    | '/surveys/$surveyId/chat'
    | '/surveys/$surveyId/fill'
    | '/surveys/$surveyId/print'
    | '/admin/surveys'
    | '/surveys/$surveyId'
    | '/admin/surveys/$surveyId/chat'
    | '/admin/surveys/$surveyId/fill'
    | '/admin/surveys/$surveyId/print'
    | '/admin/surveys/$surveyId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin/create'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/responses'
    | '/admin/signup'
    | '/admin/'
    | '/surveys/'
    | '/surveys/$surveyId/chat'
    | '/surveys/$surveyId/fill'
    | '/surveys/$surveyId/print'
    | '/admin/surveys/'
    | '/surveys/$surveyId/'
    | '/admin/surveys/$surveyId/chat'
    | '/admin/surveys/$surveyId/fill'
    | '/admin/surveys/$surveyId/print'
    | '/admin/surveys/$surveyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  SurveysIndexRoute: typeof SurveysIndexRoute
  SurveysSurveyIdChatRoute: typeof SurveysSurveyIdChatRoute
  SurveysSurveyIdFillRoute: typeof SurveysSurveyIdFillRoute
  SurveysSurveyIdPrintRoute: typeof SurveysSurveyIdPrintRoute
  SurveysSurveyIdIndexRoute: typeof SurveysSurveyIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/': {
      id: '/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof SurveysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses': {
      id: '/admin/responses'
      path: '/responses'
      fullPath: '/admin/responses'
      preLoaderRoute: typeof AdminResponsesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/surveys/$surveyId/': {
      id: '/surveys/$surveyId/'
      path: '/surveys/$surveyId'
      fullPath: '/surveys/$surveyId/'
      preLoaderRoute: typeof SurveysSurveyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/surveys'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/surveys/$surveyId/print': {
      id: '/surveys/$surveyId/print'
      path: '/surveys/$surveyId/print'
      fullPath: '/surveys/$surveyId/print'
      preLoaderRoute: typeof SurveysSurveyIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$surveyId/fill': {
      id: '/surveys/$surveyId/fill'
      path: '/surveys/$surveyId/fill'
      fullPath: '/surveys/$surveyId/fill'
      preLoaderRoute: typeof SurveysSurveyIdFillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$surveyId/chat': {
      id: '/surveys/$surveyId/chat'
      path: '/surveys/$surveyId/chat'
      fullPath: '/surveys/$surveyId/chat'
      preLoaderRoute: typeof SurveysSurveyIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/surveys/$surveyId/': {
      id: '/admin/surveys/$surveyId/'
      path: '/surveys/$surveyId'
      fullPath: '/admin/surveys/$surveyId/'
      preLoaderRoute: typeof AdminSurveysSurveyIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/$surveyId/print': {
      id: '/admin/surveys/$surveyId/print'
      path: '/surveys/$surveyId/print'
      fullPath: '/admin/surveys/$surveyId/print'
      preLoaderRoute: typeof AdminSurveysSurveyIdPrintRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/$surveyId/fill': {
      id: '/admin/surveys/$surveyId/fill'
      path: '/surveys/$surveyId/fill'
      fullPath: '/admin/surveys/$surveyId/fill'
      preLoaderRoute: typeof AdminSurveysSurveyIdFillRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/$surveyId/chat': {
      id: '/admin/surveys/$surveyId/chat'
      path: '/surveys/$surveyId/chat'
      fullPath: '/admin/surveys/$surveyId/chat'
      preLoaderRoute: typeof AdminSurveysSurveyIdChatRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCreateRoute: typeof AdminCreateRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResponsesRoute: typeof AdminResponsesRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
  AdminSurveysSurveyIdChatRoute: typeof AdminSurveysSurveyIdChatRoute
  AdminSurveysSurveyIdFillRoute: typeof AdminSurveysSurveyIdFillRoute
  AdminSurveysSurveyIdPrintRoute: typeof AdminSurveysSurveyIdPrintRoute
  AdminSurveysSurveyIdIndexRoute: typeof AdminSurveysSurveyIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateRoute: AdminCreateRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResponsesRoute: AdminResponsesRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
  AdminSurveysSurveyIdChatRoute: AdminSurveysSurveyIdChatRoute,
  AdminSurveysSurveyIdFillRoute: AdminSurveysSurveyIdFillRoute,
  AdminSurveysSurveyIdPrintRoute: AdminSurveysSurveyIdPrintRoute,
  AdminSurveysSurveyIdIndexRoute: AdminSurveysSurveyIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  SurveysIndexRoute: SurveysIndexRoute,
  SurveysSurveyIdChatRoute: SurveysSurveyIdChatRoute,
  SurveysSurveyIdFillRoute: SurveysSurveyIdFillRoute,
  SurveysSurveyIdPrintRoute: SurveysSurveyIdPrintRoute,
  SurveysSurveyIdIndexRoute: SurveysSurveyIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
